# Generated by Django 5.1.5 on 2025-06-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cartao', models.CharField(max_length=16, unique=True)),
                ('nome_cartao', models.CharField(max_length=100)),
                ('data_validade', models.CharField(max_length=5)),
                ('cvv', models.CharField(max_length=3)),
                ('saldo_debito', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_credito', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
