# Generated by Django 5.1.5 on 2025-08-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='foto',
            field=models.CharField(max_length=100),
        ),
    ]
